rabbitmq:
    image: rabbitmq:3-management
    ports:
     - 8881:15672
     - 5671:5671
     - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: senha

MongoDB:
  image: mongo:latest
  ports:
    - "27017:27017"


MongoDB2:
  image: mongo:latest
  ports:
    - "27018:27017"

